---
- name: add ppa:chris-lea/node.js for node.js installation
  apt_repository: repo=ppa:chris-lea/node.js update_cache=yes

- name: install node.js
  apt: pkg=nodejs state=latest

# Project installation
# --------------------------------------------------------------------------

- name: install brunch for assets compilation
  npm: name=brunch global=yes

- name: install fanboi2 requirements
  sudo_user: ${user}
  npm: path=${root}

# Initial compilation
# --------------------------------------------------------------------------

- name: initial assets compilation
  sudo_user: ${user}
  command: brunch build -o creates=${static} chdir=${root}

# Assets watching (in development)
# --------------------------------------------------------------------------

- include: watch.yml
  when: development == '1'
