---
- name: add ppa:nginx/stable for nginx installation
  apt_repository: repo=ppa:nginx/stable update_cache=yes

- name: install nginx
  apt: pkg=nginx state=latest

# Configuring Nginx
# --------------------------------------------------------------------------

- name: setup nginx configuration
  template: src=etc/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: cleanup default nginx configuration file
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
