---
- name: add official postgresql ubuntu repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
    state: present

- name: add official postgresql ubuntu repository key
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: update apt for new repository
  command: aptitude update creates=/etc/init.d/postgresql

- name: install postgresql and its related packages
  apt: pkg=${item} state=latest
  with_items:
    - postgresql-9.2
    - libpq-dev
    - python-psycopg2

# Creating PostgreSQL databases
# --------------------------------------------------------------------------

- name: create database user for application
  sudo_user: postgres
  postgresql_user:
    user: ${db_user}
    password: ${db_pass}

- name: create database for application
  sudo_user: postgres
  postgresql_db:
    db: ${item}
    owner: ${db_user}
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
  with_items:
    - ${db_name}
    - ${db_test}

# Configuring PostgreSQL
# --------------------------------------------------------------------------

- name: update postgresql configuration file
  template:
    src: etc/postgresql/9.2/main/postgresql.conf.j2
    dest: /etc/postgresql/9.2/main/postgresql.conf
  notify: restart postgresql

- name: update pg_hba to allow appservers
  template:
    src: etc/postgresql/9.2/main/pg_hba.conf.j2
    dest: /etc/postgresql/9.2/main/pg_hba.conf
  notify: restart postgresql
