---
- name: add official postgresql ubuntu repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
    state: present

- name: add official postgresql ubuntu repository key
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: update apt for new repository
  command: aptitude update creates=/etc/init.d/postgresql

- name: install postgresql and its related packages
  apt: pkg=${item} state=latest
  with_items:
    - postgresql-9.2
    - libpq-dev
    - python-psycopg2

# Creating PostgreSQL databases
# --------------------------------------------------------------------------

- name: create database user for application
  sudo_user: postgres
  postgresql_user:
    user: ${postgresql.username}
    password: ${postgresql.password}

- name: create database for application
  sudo_user: postgres
  postgresql_db:
    db: ${item}
    owner: ${postgresql.username}
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
  with_items:
    - ${postgresql.name}
    - ${postgresql.test}
