---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure all package are latest
      apt: update_cache=yes upgrade=safe cache_valid_time=604800

    - name: install python-software-properties for ppa support
      apt: pkg=python-software-properties state=latest

    # Setup workspace.
    # ---------------------------------------------------------------------

    - name: create a working directory
      file: path=${base} state=directory

    - name: link vagrant path to server directory for development
      file: src=/vagrant dest=${root} state=link
      when: development == '1'


- hosts: webservers
  sudo: yes
  roles:
    - role: webservers
    - role: pgservers
    - role: redisservers
    - role: appservers
    - role: assetsservers
