---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure package index is latest
      apt: update_cache=yes cache_valid_time=604800
      register: package_updated

    - name: ensure all packages are up-to-date
      apt: upgrade=safe
      when: package_updated.changed

    - name: install python-software-properties for ppa support
      apt: pkg=python-software-properties state=latest

    # Setup workspace.
    # ---------------------------------------------------------------------

    - name: create a working directory
      file: path=${base} state=directory

    - name: link vagrant path to server directory for development
      file: src=/vagrant dest=${root} state=link
      when: development == '1'


- hosts: webservers
  sudo: yes
  roles:
    - role: webservers
    - role: pgservers
    - role: redisservers
    - role: appservers
    - role: assetsservers
