---
- name: install python3 and related packages
  apt: pkg=${item} state=latest
  with_items:
    - python3.2
    - python3.2-dev
    - python3-setuptools
    - build-essential
    - libpq-dev
    - git

- name: install python3 requisites
  command: |
    easy_install3 ${item}
    creates=/usr/local/bin/${item}-3.2
  with_items:
    - pip
    - virtualenv

# Setup environment.
# ---------------------------------------------------------------------

- name: creates application directory
  file: path=${base} owner=${user} state=directory

- name: fix /var/www permission
  file: path=/var/www owner=${user} group=root state=directory

- name: setup virtualenv for application directory
  sudo_user: ${user}
  command: |
    virtualenv -p python3 ${virtualenv}
    creates=${virtualenv}

# uWSGI setup
# ---------------------------------------------------------------------

- name: install uwsgi to system python
  pip: name=uwsgi

- name: ensure that uwsgi configuration dir exists
  file: path=/etc/uwsgi state=directory

- name: start uwsgi with upstart
  copy: src=etc/init/uwsgi.conf dest=/etc/init/uwsgi.conf
  notify: restart uwsgi

# Application setup
# ---------------------------------------------------------------------

- name: check installation status for fanboi2
  register: fanboi2_installed
  shell: ${virtualenv}/bin/python3 -c 'import fanboi2' && echo '1' || echo '0'
  changed_when: fanboi2_installed.stdout == '0'

- name: install application in development mode
  sudo_user: ${user}
  command: |
    env LANG=en_US.UTF-8 ${virtualenv}/bin/pip-3.2 install -e . --use-mirrors
    chdir=${root}
  when: fanboi2_installed.stdout == '0'

- name: create configuration file for application
  sudo_user: ${user}
  template: src=srv/settings.ini.j2 dest=${base}/settings.ini

- name: create configuration file for alembic
  sudo_user: ${user}
  template: src=srv/alembic.ini.j2 dest=${base}/alembic.ini

- name: create uwsgi file for application
  sudo_user: ${user}
  template: src=srv/fanboi2.wsgi.j2 dest=${base}/fanboi2.wsgi

- name: sync database to latest version
  sudo_user: ${user}
  command: ${virtualenv}/bin/alembic upgrade head chdir=${base}
  when: fanboi2_installed.stdout == '0'

# Application startup
# ---------------------------------------------------------------------

- name: startup application with uwsgi
  template: src=etc/uwsgi/fanboi2.ini.j2 dest=/etc/uwsgi/fanboi2.ini
  notify: restart uwsgi
