---
- name: install python3 and related packages
  apt: pkg=${item} state=latest
  with_items:
    - python3.2
    - python3.2-dev
    - python3-setuptools
    - build-essential
    - libpq-dev
    - git

- name: install python3 requisites
  command: |
    easy_install3 ${item}
    creates=/usr/local/bin/${item}-3.2
  with_items:
    - pip
    - virtualenv

# Setup environment.
# ---------------------------------------------------------------------

- name: ensure that user to run the app exists
  user: name=${user} state=present

- name: creates application directory
  file: path=${app.base} owner=${user} state=directory

- name: setup virtualenv for application directory
  sudo: no
  command: |
    virtualenv -p python3 ${app.virtualenv}
    creates=${app.virtualenv}

# Application setup
# ---------------------------------------------------------------------

# TODO: Remove me after requests 1.2.4 is released. See also:
# https://github.com/kennethreitz/requests/issues/1416
#
- name: install git version of requests
  sudo: no
  pip:
    name: "git+https://github.com/kennethreitz/requests#egg=requests"
    virtualenv: ${app.virtualenv}

- name: install application in development mode
  sudo: no
  command: |
    env LANG=en_US.UTF-8 ${app.virtualenv}/bin/python3 setup.py develop
    chdir=${app.root}
    creates=${app.root}/fanboi2.egg-info
