---
- name: install python3 and related packages
  apt: pkg=${item} state=latest
  with_items:
    - python3.2
    - python3.2-dev
    - python3-setuptools
    - build-essential
    - libpq-dev
    - git

- name: install python3 requisites
  command: |
    easy_install3 ${item}
    creates=/usr/local/bin/${item}-3.2
  with_items:
    - pip
    - virtualenv

# Setup environment.
# ---------------------------------------------------------------------

- name: ensure that user to run the app exists
  user: name=www-data home=/var/www state=present

- name: creates application directory
  file: path=${base} owner=www-data state=directory

- name: fix /var/www permission
  file: path=/var/www owner=www-data group=root state=directory

- name: setup virtualenv for application directory
  sudo_user: www-data
  command: |
    virtualenv -p python3 ${virtualenv}
    creates=${virtualenv}

# uWSGI setup
# ---------------------------------------------------------------------

- name: install uwsgi to system python
  pip: name=uwsgi

- name: ensure that uwsgi configuration dir exists
  file: path=/etc/uwsgi state=directory

- name: start uwsgi with upstart
  copy: src=etc/init/uwsgi.conf dest=/etc/init/uwsgi.conf
  notify: restart uwsgi

# Application setup
# ---------------------------------------------------------------------

# TODO: Remove me after requests 1.2.4 is released. See also:
# https://github.com/kennethreitz/requests/issues/1416

- name: install git version of requests
  sudo_user: www-data
  pip:
    name: "git+https://github.com/kennethreitz/requests#egg=requests"
    virtualenv: ${virtualenv}

- name: install application in development mode
  sudo_user: www-data
  command: |
    env LANG=en_US.UTF-8 ${virtualenv}/bin/python3 setup.py develop
    chdir=${root}
    creates=${virtualenv}/bin/fb2_create_board

# Application configuration
# ---------------------------------------------------------------------

- name: create configuration file for application
  sudo_user: www-data
  template: src=srv/settings.ini.j2 dest=${base}/settings.ini

- name: create configuration file for alembic
  sudo_user: www-data
  template: src=srv/alembic.ini.j2 dest=${base}/alembic.ini

- name: create uwsgi file for application
  sudo_user: www-data
  template: src=srv/fanboi2.wsgi.j2 dest=${base}/fanboi2.wsgi

# Application startup
# ---------------------------------------------------------------------

- name: startup application with uwsgi
  template: src=etc/uwsgi/fanboi2.ini.j2 dest=/etc/uwsgi/fanboi2.ini
  notify: restart uwsgi
